// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(CsdlDuAn1Context))]
    partial class CsdlDuAn1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Data.ChucVu", b =>
                {
                    b.Property<string>("IdchucVu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDChucVu");

                    b.Property<string>("ChucVu1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ChucVu");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdchucVu")
                        .HasName("PK__ChucVu__70FCCF6575380A7B");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("Data.Data.HoaDon", b =>
                {
                    b.Property<string>("IdhoaDon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDHoaDon");

                    b.Property<string>("IdkhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDKhachHang");

                    b.Property<string>("IdnhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDNhanVien");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<int?>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.HasKey("IdhoaDon")
                        .HasName("PK__HoaDon__5B896F49AAB9A637");

                    b.HasIndex("IdkhachHang");

                    b.HasIndex("IdnhanVien");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Data.Data.HoaDonChiTiet", b =>
                {
                    b.Property<string>("IdhoaDonChiTiet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDHoaDonChiTiet");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("money");

                    b.Property<string>("IdhoaDon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDHoaDon");

                    b.Property<string>("IdsanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDSanPham");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdhoaDonChiTiet")
                        .HasName("PK__HoaDonCh__21C23677EBC90804");

                    b.HasIndex("IdhoaDon");

                    b.HasIndex("IdsanPham");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("Data.Data.KhachHang", b =>
                {
                    b.Property<string>("IdkhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDKhachHang");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("Sdt")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Ten")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdkhachHang")
                        .HasName("PK__KhachHan__5A7167B5F4553D76");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Data.Data.KhuyenMai", b =>
                {
                    b.Property<string>("IdkhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDKhuyenMai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<double?>("PhanTramGiamGia")
                        .HasColumnType("float");

                    b.Property<bool?>("TamNgung")
                        .HasColumnType("bit");

                    b.Property<string>("TenKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdkhuyenMai")
                        .HasName("PK__KhuyenMa__FFAC140028E455BE");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Data.Data.LoaiSanPham", b =>
                {
                    b.Property<string>("IdloaiSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDLoaiSanPham");

                    b.Property<string>("IdkhuyenMai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDKhuyenMai");

                    b.Property<string>("LoaiSanPham1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiSanPham");

                    b.HasKey("IdloaiSanPham")
                        .HasName("PK__LoaiSanP__6CB987C502692B2F");

                    b.HasIndex("IdkhuyenMai");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("Data.Data.NhanVien", b =>
                {
                    b.Property<string>("IdnhanVien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDNhanVien");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("IdchucVu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDChucVu");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThaiLamViec")
                        .HasColumnType("bit");

                    b.HasKey("IdnhanVien")
                        .HasName("PK__NhanVien__7AC2D9F753DE7605");

                    b.HasIndex("IdchucVu");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Data.Data.SanPham", b =>
                {
                    b.Property<string>("IdsanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDSanPham");

                    b.Property<string>("ChiSoFa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ChiSoFA");

                    b.Property<string>("ChiSoSpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ChiSoSPF");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("money");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("money");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<string>("IdloaiSanPham")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDLoaiSanPham");

                    b.Property<double?>("KhoiLuong")
                        .HasColumnType("float");

                    b.Property<string>("NguonGoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdsanPham")
                        .HasName("PK__SanPham__9D45E58A643DF533");

                    b.HasIndex("IdloaiSanPham");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("Data.Data.ThanhTien", b =>
                {
                    b.Property<string>("IdthanhTien")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDThanhTien");

                    b.Property<string>("IdhoaDon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDHoaDon");

                    b.Property<decimal?>("KhuyenMai")
                        .HasColumnType("money");

                    b.Property<decimal?>("ThanhTien1")
                        .HasColumnType("money")
                        .HasColumnName("ThanhTien");

                    b.Property<decimal?>("TienKhachDua")
                        .HasColumnType("money");

                    b.Property<decimal?>("TienThua")
                        .HasColumnType("money");

                    b.Property<decimal?>("TongHoaDon")
                        .HasColumnType("money");

                    b.HasKey("IdthanhTien")
                        .HasName("PK__ThanhTie__34C64E685744273A");

                    b.HasIndex("IdhoaDon");

                    b.ToTable("ThanhTien", (string)null);
                });

            modelBuilder.Entity("Data.Data.HoaDon", b =>
                {
                    b.HasOne("Data.Data.KhachHang", "IdkhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdkhachHang")
                        .HasConstraintName("FK__HoaDon__IDKhachH__5535A963");

                    b.HasOne("Data.Data.NhanVien", "IdnhanVienNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdnhanVien")
                        .HasConstraintName("FK__HoaDon__IDNhanVi__5629CD9C");

                    b.Navigation("IdkhachHangNavigation");

                    b.Navigation("IdnhanVienNavigation");
                });

            modelBuilder.Entity("Data.Data.HoaDonChiTiet", b =>
                {
                    b.HasOne("Data.Data.HoaDon", "IdhoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdhoaDon")
                        .HasConstraintName("FK__HoaDonChi__IDHoa__5EBF139D");

                    b.HasOne("Data.Data.SanPham", "IdsanPhamNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdsanPham")
                        .HasConstraintName("FK__HoaDonChi__IDSan__5FB337D6");

                    b.Navigation("IdhoaDonNavigation");

                    b.Navigation("IdsanPhamNavigation");
                });

            modelBuilder.Entity("Data.Data.LoaiSanPham", b =>
                {
                    b.HasOne("Data.Data.KhuyenMai", "IdkhuyenMaiNavigation")
                        .WithMany("LoaiSanPhams")
                        .HasForeignKey("IdkhuyenMai")
                        .HasConstraintName("FK__LoaiSanPh__IDKhu__4BAC3F29");

                    b.Navigation("IdkhuyenMaiNavigation");
                });

            modelBuilder.Entity("Data.Data.NhanVien", b =>
                {
                    b.HasOne("Data.Data.ChucVu", "IdchucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdchucVu")
                        .HasConstraintName("FK__NhanVien__IDChuc__5070F446");

                    b.Navigation("IdchucVuNavigation");
                });

            modelBuilder.Entity("Data.Data.SanPham", b =>
                {
                    b.HasOne("Data.Data.LoaiSanPham", "IdloaiSanPhamNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdloaiSanPham")
                        .HasConstraintName("FK__SanPham__IDLoaiS__5BE2A6F2");

                    b.Navigation("IdloaiSanPhamNavigation");
                });

            modelBuilder.Entity("Data.Data.ThanhTien", b =>
                {
                    b.HasOne("Data.Data.HoaDon", "IdhoaDonNavigation")
                        .WithMany("ThanhTiens")
                        .HasForeignKey("IdhoaDon")
                        .HasConstraintName("FK__ThanhTien__IDHoa__59063A47");

                    b.Navigation("IdhoaDonNavigation");
                });

            modelBuilder.Entity("Data.Data.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Data.Data.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("ThanhTiens");
                });

            modelBuilder.Entity("Data.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Data.Data.KhuyenMai", b =>
                {
                    b.Navigation("LoaiSanPhams");
                });

            modelBuilder.Entity("Data.Data.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Data.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Data.Data.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
